export default {
    kor: {
        loading: '요청 중',
        welcomeBack: '환영하세요',
        httpFail: '요청 실패: 서버 요청 오류',
        salesCount: '판매 수량',
        salesAmount: '판매 금액',
        refundsCount: '환불 수량',
        refundsAmount: '환불 금액',
        actualSalesAmount: '실 판매 금액',
        income: '순 수액',
        yuan: 'CNY',
        piece: '개',
        recentData: '최근 데이터',
        unUpload: '전일 판매 미 업로드',
        upload: '업로드',
        recommend: '추천'
    },
    jp: {
        loading: '読み込み中',
        welcomeBack: 'ようこそ',
        httpFail: 'HTTP 失敗: サーバー 要求 エラー',
        salesCount: '販売 数',
        salesAmount: '販売 額',
        refundsCount: '返金 数',
        refundsAmount: '返金 額',
        actualSalesAmount: '実 販売 額',
        income: '順 額',
        yuan: 'CNY',
        piece: '枚',
        recentData: '最近 データ',
        unUpload: '前日 販売 未 アップロード',
        upload: 'アップロード',
        recommend: '推薦'
    },
    th: {
        loading: 'การโหลดข้อมูล',
        welcomeBack: 'สวัสดี',
        httpFail: 'การโหลดข้อมูลไม่สำเร็จ: การสั่งซื้อออก',
        salesCount: 'ข้อมูลการขาย',
        salesAmount: 'ออกไฟเฟอร์',
        refundsCount: 'ข้อมูลการคนนำ',
        refundsAmount: 'ออกไฟเฟอร์',
        actualSalesAmount: 'ไฟเฟอร์',
        income: 'ไฟเฟอร์',
        yuan: 'CNY',
        piece: 'ชิ้น',
        recentData: 'ข้อมูลเมื่อเมื่อ',
        unUpload: 'การขายไม่ได้ออก',
        upload: 'ออก',
        recommend: 'เนื้อมา'
    }
}